# ----
# Site

title: RocketJourney Documentation
description: Documentation for the RocketJourney Platform
url: https://rocketjourney.github.io/docs/
google_analytics_key:
permalink: pretty

collections:
  intro:
    title: Introduction
    position: 1
  exampleintro:
    title: Example Intro
    position: 2
  exampleapi:
    title: Example APIs
    position: 3
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
