# ----
# Site

title: RocketJourney Documentation
description: Documentation for the RocketJourney Platform
url: https://rocketjourney.github.io/docs/
google_analytics_key:
permalink: pretty

collections:
  intro:
    title: Introduction
    position: 1
  member-verification:
    title: Member Verification
    position: 2
  checkin-verification:
    title: Check-In Verification
    position: 3
  examples:
    title: Examples
    position: 4
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
